### ISSUE TITLE
Allowing us to Download all the music files for offline use.

### ISSUE THREAD

**Issue by mitfry** [maplestory-music/maplebgm-db#10]
Hi there! 

First and foremost, thank you for all your work in collecting all the music and keeping the database up-to-date. To get the most out of it, I'd like to download all the music for offline usage.

Is it already possible to download all the music and have I missed a link or something, or is it something you could setup? For example in MP3 format.

**Comment by nanochromatic** [comment]
Unfortunately, download links will not be provided due to copyright restrictions. NECORD has been distributing the music since 2016 and remain the only official distributor of the songs. The music is permitted on YouTube since the copyright holder is able to monetize that medium.
