### ISSUE TITLE
Other MapleStory Games?

### ISSUE THREAD

**Issue by seth1** [maplestory-music/maplebgm-db#15]
I notice the DB has tracks from the Website about MapleStory, but I'm wondering if within the project's scope would be games like MapleStory 2, MapleStory 3/DS, etc.

A comprehensive list would be:
 - MapleStory 2
 - MapleStory DS
 - MapleStory 3DS (Intro/player death sound, maybe more?)
 - Early MapleStory Mobile games (Warrior, Thief, Archer, Magician, 2007)
 - MapleStory Chinese Horoscope (contains some public domain song as a theme)
 - MapleStory Cave Story
 - Online iTCG
 - AngelMaple Flash games (not actually sure if there's a new soundtrack in them)
 - MapleStory Anime (theme song, maybe the DVDs have some menu theme but I don't know)

I don't think MapleStory Live/M/Cygnus/Thief had any new soundtracks, but I could be mistaken.

**Comment by nanochromatic** [comment]
The project's primary scope focuses on music found within the data files of MapleStory. Sometimes, website tracks may be included if they are complementary to musical works within the game. Other works within the franchise would not be included in the project's scope.

MapleStory M does have exclusive music. Here's one such [album](https://www.youtube.com/playlist?list=PLrgkfqG7JAcPFqoVkbhG_SnsfqoX3ngmg).
